### ISSUE TITLE
Create basic Gaucho Gardens Webbapp template for app (100 points)

### ISSUE THREAD

**Issue by chrislianides** [ucsb-cs56-f18/ucsb-cs56-gaucho-gardens#1]
Create basic Gaucho Gardens Webbapp template bootstrap navigation (as illustrated in lab06), but have menu item that says:

-List of plants to grow (issue assigned to: Chris, jay, jaci, daniel and Anna

and have that link go to a page that says "coming soon" as a placeholder

https://github.com/ucsb-cs56-webapps/ucsb-cs56-gaucho-gardens/pull/2#issue-236010793

**Comment by meredithxu** [comment]
Mentor Approved 100 pts

**Comment by chrislianides** [comment]
seasonal plants tab will display the list of plants gauchos can attempt to grow on their own.
