### ISSUE TITLE
Create selection feature from list (200 points for now and 400 points if database is involved)

### ISSUE THREAD

**Issue by chrislianides** [ucsb-cs56-f18/ucsb-cs56-gaucho-gardens#3]
Allow selection from list of plants

Assigned to: Jay, Anna, Jaci

https://github.com/ucsb-cs56-webapps/ucsb-cs56-gaucho-gardens/pull/2#issue-236010793

**Comment by meredithxu** [comment]
Can you expand on this issue a little bit? Does creating selection feature just mean displaying a list of clickable links of plants or does it also include displaying the information of a plant that user selects after the link is clicked?

**Comment by meredithxu** [comment]
Mentor Approved 200 pts

**Comment by chrislianides** [comment]
database was involved
