### ISSUE TITLE
Find information and construct database of plants (150 points)

### ISSUE THREAD

**Issue by chrislianides** [ucsb-cs56-f18/ucsb-cs56-gaucho-gardens#4]
Find and construct database of plants

assigned to: everyone

https://github.com/ucsb-cs56-webapps/ucsb-cs56-gaucho-gardens/pull/2#issue-236010793

**Comment by meredithxu** [comment]
Mentor Approved 150 pts

**Comment by chrislianides** [comment]
made 5 plants
