### ISSUE TITLE
Fill in the weather/map page to display local weather on an interactive map (300 points)

### ISSUE THREAD

**Issue by jacquelinehuang** [ucsb-cs56-f18/ucsb-cs56-gaucho-gardens#8]
https://github.com/ucsb-cs56-webapps/ucsb-cs56-gaucho-gardens/pull/2#issue-236010793

**Comment by meredithxu** [comment]
Mentor Approved: 300 pts

**Comment by jacquelinehuang** [comment]
https://github.com/ucsb-cs56-webapps/ucsb-cs56-gaucho-gardens/pull/1
